services:
  datahub:
    image: ghcr.io/datasnack/datahub:latest
    env_file:
      - .env
    ports:
      - ${DATAHUB_PORT:-8000}:8000
    volumes:
      - ./data:/app/data/
      - ./src:/app/src/

  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdat
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  ollama:
    image: ollama/ollama
    ports:
     - 11434:11434/tcp
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all # alternatively, use `all` for all GPUs
    #           capabilities: [gpu]

volumes: 
  ollama:
